In [2]:
import requests
from PIL import Image
from io import BytesIO
import pandas as pd
from transformers import CLIPProcessor, CLIPModel
import torch

import glob

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [12]:
df=pd.read_csv("/Users/kunkerdthaisong/cils/bangkok_traffy.csv")
df=df.dropna(subset=["type"])
df=df[df["type"].str.contains("ท่อ")] #30288 rows

In [13]:
df

ticket_id                                             type  \
5       2021-8Z8JQ3  {ท่อระบายน้ำ,ถนน,ร้องเรียน,ความปลอดภัย,น้ำท่วม}   
9       2021-Q7XMCN                        {ความปลอดภัย,ท่อระบายน้ำ}   
14      2021-F7A2PK                        {ความปลอดภัย,ท่อระบายน้ำ}   
38      2021-FUM99G                      {ทางเท้า,ท่อระบายน้ำ,สายไฟ}   
39      2021-4K7APR                        {ถนน,ทางเท้า,ท่อระบายน้ำ}   
...             ...                                              ...   
500149  2024-GCUPMP                        {ท่อระบายน้ำ,ถนน,ทางเท้า}   
500154  2024-686U3W                                    {ท่อระบายน้ำ}   
500173  2024-F2GGGL                            {ท่อระบายน้ำ,กีดขวาง}   
500186  2024-GKLB7V              {ท่อระบายน้ำ,ถนน,ร้องเรียน,น้ำท่วม}   
500196  2024-GGZTGB                                    {ท่อระบายน้ำ}   

                                             organization  \
5                                                     NaN   
9                                                     NaN   
14                                                    NaN   
38                                                    NaN   
39                                                    NaN   
...                                                   ...   
500149  บริษัท โทรคมนาคมแห่งชาติ จำกัด (มหาชน),เขตบึงกุ่ม   
500154                       ฝ่ายโยธา เขตจอมทอง,เขตจอมทอง   
500173                                     เขตบางขุนเทียน   
500186                 ฝ่ายเทศกิจ เขตห้วยขวาง,เขตห้วยขวาง   
500196                                          เขตประเวศ   

                                                  comment  \
5       1) พื้นที่นี้ขาดหน่วยงานรับผิดชอบ เนื่องจากไม่...   
9       งานไม่เสร็จ ควรเก็บท่อHDPE ทั้งการวางการมัดท่อ...   
14      มีฝาท่อระบายน้ำชำรุดบริเวณ ซ.เพชรเกษม46 ช่วงตร...   
38      ทางเท้า ตามพิกัด มีฝาท่อเปิด และมีสายไฟ,เคเบิ้...   
39      ฟุตบาทถนนเทพรักษ์ (ถนนเส้นตัดใหม่ตรงbig c สะพา...   
...                                                   ...   
500149  ฝาท่อระบายน้ำชำรุดบนบาทวิถีทางเท้าฟุตปาธครับบร...   
500154        ท่ออุดตันมีน้ำขัง อาจเป็นแหล่งบ่อเกิดยุงลาย   
500173          ตั้งร้านกีดขวางทางเดิน กีดขวางท่อระบายน้ำ   
500186  ท่อระบายน้ำปากซอยพระรามเก้า13 หักจุดเชื่อมต่อท...   
500196             ฝาท่อระบายน้ำที่เป็นปูนในซอยบ้านแตกค่ะ   

                                                    photo  \
5       https://storage.googleapis.com/traffy_public_b...   
9       https://storage.googleapis.com/traffy_public_b...   
14      https://storage.googleapis.com/traffy_public_b...   
38      https://storage.googleapis.com/traffy_public_b...   
39      https://storage.googleapis.com/traffy_public_b...   
...                                                   ...   
500149  https://storage.googleapis.com/traffy_public_b...   
500154  https://storage.googleapis.com/traffy_public_b...   
500173  https://storage.googleapis.com/traffy_public_b...   
500186  https://storage.googleapis.com/traffy_public_b...   
500196  https://storage.googleapis.com/traffy_public_b...   

                                              photo_after              coords  \
5                                                     NaN  100.86190,13.72804   
9                                                     NaN  100.50779,13.79675   
14                                                    NaN  100.44755,13.71937   
38                                                    NaN  100.42688,13.78080   
39                                                    NaN  100.60634,13.89027   
...                                                   ...                 ...   
500149                                                NaN  100.64896,13.81050   
500154  https://storage.googleapis.com/traffy_public_b...  100.47535,13.70117   
500173                                                NaN  100.44853,13.65287   
500186                                                NaN  100.58746,13.75414   
500196                                                N

In [7]:
model = CLIPModel.from_pretrained("openai/clip-vit-large-patch14")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-large-patch14")

In [25]:
def run(image):
        inputs =processor(
            text=["manhole","manhole cover","sink hole","road","not road"], #text=["flood", "flooded road", "water on floor", "road", "no water","dried road"],
            images=image,
            return_tensors="pt",
            padding=True
        )
        with torch.no_grad():
            outputs =model(**inputs)
            logits_per_image = outputs.logits_per_image
            probs = logits_per_image.softmax(dim=1)
        return probs

In [30]:

#read image from url
def read_and_save_image(url, save_path):

    response = requests.get(url)
    if response.status_code == 200:
        image = Image.open(BytesIO(response.content))
        probs=run(image)
        if probs.squeeze(0)[:3].sum()>0.5 and probs.squeeze(0)[-1:].sum()<0.2: #probs.squeeze(0)[1] >0.3 and probs.squeeze(0)[:3].sum()>0.55 and probs.squeeze(0)[-2:].sum()<0.25:
            image.save(save_path)
            return probs
    else:
        print(f"Failed to download image from URL: {url}")
        

In [31]:
count=0
for i in df["photo"][0:]:
    save_path = f"/Users/kunkerdthaisong/cils/images2/{count}.jpg"
    read_and_save_image(i, save_path)
    count+=1

tensor([2.6878e-01, 2.9546e-01, 4.3248e-01, 3.5973e-04, 2.9184e-03])
tensor([2.6878e-01, 2.9546e-01, 4.3248e-01, 3.5973e-04, 2.9184e-03])
tensor([2.6878e-01, 2.9546e-01, 4.3248e-01, 3.5973e-04, 2.9184e-03])
tensor([2.6878e-01, 2.9546e-01, 4.3248e-01, 3.5973e-04, 2.9184e-03])
tensor([2.6878e-01, 2.9546e-01, 4.3248e-01, 3.5973e-04, 2.9184e-03])
tensor([2.6878e-01, 2.9546e-01, 4.3248e-01, 3.5973e-04, 2.9184e-03])
tensor([2.6878e-01, 2.9546e-01, 4.3248e-01, 3.5973e-04, 2.9184e-03])
tensor([2.6878e-01, 2.9546e-01, 4.3248e-01, 3.5973e-04, 2.9184e-03])
tensor([2.6878e-01, 2.9546e-01, 4.3248e-01, 3.5973e-04, 2.9184e-03])
tensor([2.6878e-01, 2.9546e-01, 4.3248e-01, 3.5973e-04, 2.9184e-03])
tensor([2.6878e-01, 2.9546e-01, 4.3248e-01, 3.5973e-04, 2.9184e-03])
tensor([2.6878e-01, 2.9546e-01, 4.3248e-01, 3.5973e-04, 2.9184e-03])


KeyboardInterrupt: 

In [68]:
count

3709

In [70]:
df

ticket_id                                             type  \
4       2021-CGPMUN                              {น้ำท่วม,ร้องเรียน}   
5       2021-8Z8JQ3  {ท่อระบายน้ำ,ถนน,ร้องเรียน,ความปลอดภัย,น้ำท่วม}   
7       2021-AFJYNF                                    {ถนน,น้ำท่วม}   
8       2021-HAJULK                          {น้ำท่วม,ถนน,ร้องเรียน}   
12      2021-9U2NJT                                        {น้ำท่วม}   
...             ...                                              ...   
499881  2024-CGUG86                                        {น้ำท่วม}   
500019  2024-EU9VCX                          {ความสะอาด,น้ำท่วม,ถนน}   
500049  2024-EV3TH7                                        {น้ำท่วม}   
500186  2024-GKLB7V              {ท่อระบายน้ำ,ถนน,ร้องเรียน,น้ำท่วม}   
500228  2024-87CYD8                                    {ถนน,น้ำท่วม}   

                                             organization  \
4                            เขตประเวศ,ฝ่ายโยธา เขตประเวศ   
5                                                     NaN   
7                                                     NaN   
8                                                     NaN   
12                         เขตบางซื่อ,ฝ่ายโยธา เขตบางซื่อ   
...                                                   ...   
499881  ฝ่ายโยธา เขตจอมทอง,เขตจอมทอง,พนักงานกวาด เขตจอ...   
500019                                         เขตหนองจอก   
500049                     สำนักสิ่งแวดล้อม กทม.,เขตดุสิต   
500186                 ฝ่ายเทศกิจ เขตห้วยขวาง,เขตห้วยขวาง   
500228              พนักงานกวาด เขตลาดกระบัง,เขตลาดกระบัง   

                                                  comment  \
4       น้ำท่วมเวลาฝนตกและทะลุเข้าบ้านเดือดร้อนมากทุกๆ...   
5       1) พื้นที่นี้ขาดหน่วยงานรับผิดชอบ เนื่องจากไม่...   
7       น้ำท่วม เอ่อล้นถนน น้ำระบายไม่ทัน บริเวณถ.พัฒน...   
8       มีการยกถนนในซอยเมื่อหลายปีที่แล้ว ทำให้บ้านอยู...   
12                                                น้ำท่วม   
...                                                   ...   
499881  น้ำท้วมขังไม่ระบายจนเกิดเป็นตะกอน ตะไคร่ ความส...   
500019  ท่อน้ำทิ้งตัน ทำให้น้ำเอ่อขึ้นถนน ทำให้ส่งกลิ่...   
500049  กทมนำถังน้ำมาให้ที่ชุมนุมเมื่อวันจันทร์ ยังไม่...   
500186  ท่อระบายน้ำปากซอยพระรามเก้า13 หักจุดเชื่อมต่อท...   
500228  น้ำท่วมขังถนน ความสูงระดับข้อเท้า น้ำท่วมมาแล้...   

                                                    photo  \
4       https://storage.googleapis.com/traffy_public_b...   
5       https://storage.googleapis.com/traffy_public_b...   
7       https://storage.googleapis.com/traffy_public_b...   
8       https://storage.googleapis.com/traffy_public_b...   
12      https://storage.googleapis.com/traffy_public_b...   
...                                                   ...   
499881  https://storage.googleapis.com/traffy_public_b...   
500019  https://storage.googleapis.com/traffy_public_b...   
500049  https://storage.googleapis.com/traffy_public_b...   
500186  https://storage.googleapis.com/traffy_public_b...   
500228  https://storage.googleapis.com/traffy_public_b...   

                                              photo_after              coords  \
4       https://storage.googleapis.com/traffy_public_b...  100.66709,13.67891   
5                                                     NaN  100.86190,13.72804   
7                                                     NaN  100.71592,13.73614   
8                                                     NaN  100.71661,13.79225   
12      https://storage.googleapis.com/traffy_public_b...  100.53099,13.81853   
...                                                   ...                 ...   
499881  https://storage.googleapis.com/traffy_public_b...  100.47532,13.70119   
500019                                                NaN  100.81994,13.84463   
500049                                                NaN  100.51341,13.76294   
500186                                                NaN  100.58746,13.75414   
500228                                                N

In [73]:
img_list=glob.glob("/Users/kunkerdthaisong/cils/images/*.jpg")
len(img_list)

2379

In [90]:
num_list=[]
for i in img_list:
    num_list.append(int(i.split("/")[-1].split(".j")[0]))
    

In [94]:
num_list=sorted(num_list)

In [95]:
num_list

[0,
 1,
 2,
 4,
 5,
 7,
 11,
 15,
 18,
 19,
 20,
 22,
 23,
 24,
 25,
 35,
 45,
 47,
 52,
 53,
 57,
 60,
 63,
 65,
 66,
 67,
 73,
 74,
 75,
 76,
 78,
 81,
 85,
 90,
 92,
 96,
 101,
 105,
 108,
 111,
 112,
 115,
 116,
 117,
 119,
 120,
 121,
 124,
 130,
 131,
 132,
 134,
 136,
 137,
 138,
 141,
 142,
 143,
 146,
 147,
 150,
 153,
 154,
 157,
 158,
 159,
 165,
 168,
 169,
 171,
 172,
 175,
 179,
 183,
 185,
 186,
 188,
 202,
 203,
 209,
 212,
 219,
 223,
 225,
 226,
 227,
 229,
 230,
 231,
 233,
 236,
 237,
 239,
 240,
 244,
 249,
 253,
 254,
 257,
 265,
 266,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 281,
 284,
 286,
 290,
 292,
 293,
 300,
 312,
 313,
 317,
 321,
 326,
 328,
 336,
 337,
 338,
 339,
 340,
 342,
 344,
 345,
 346,
 349,
 350,
 351,
 352,
 353,
 357,
 361,
 366,
 377,
 379,
 384,
 385,
 387,
 388,
 389,
 391,
 392,
 393,
 397,
 400,
 401,
 404,
 406,
 407,
 409,
 422,
 424,
 428,
 434,
 437,
 439,
 444,
 445,
 448,
 450,
 454,
 455,
 459,
 460,
 467,
 472,
 473,
 474

In [100]:
df2=df.iloc[num_list]

In [107]:
df3=df2.reset_index()

In [112]:
df3.to_csv("/Users/kunkerdthaisong/cils/flooded_road.csv")

In [110]:
df3["photo"][3]

'https://storage.googleapis.com/traffy_public_bucket/attachment/2021-10/5a36fa060eb2a750e3ff47cdd30307f4639f445e.jpg'

In [111]:
response = requests.get(df3["photo"][3])
image = Image.open(BytesIO(response.content))
image.show()

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
